# Generated by Django 2.1.4 on 2019-01-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('n_grams', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharacterTypes',
            new_name='CharacterType',
        ),
        migrations.RenameModel(
            old_name='WordTypes',
            new_name='WordType',
        ),
    ]
