# Generated by Django 2.1.4 on 2019-01-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n_grams', '0004_auto_20190103_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='document_upload/'),
        ),
    ]
